name: Build node_exporter
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install requirementes
        run: python -m pip install -r requirements.txt
      - name: Unit test
        run: python -m unittest discover tests "test_*.py"
      - run: pip install wheel
      - run: python setup.py bdist_wheel
      - name: Publish package
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}
